// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// fascicleReaders.h
cpp11::writable::list ReadVTK(const std::string & inputTracts);
extern "C" SEXP _riot_ReadVTK(SEXP inputTracts) {
  BEGIN_CPP11
    return cpp11::as_sexp(ReadVTK(cpp11::as_cpp<cpp11::decay_t<const std::string &>>(inputTracts)));
  END_CPP11
}
// fascicleReaders.h
cpp11::writable::list ReadVTP(const std::string & inputTracts);
extern "C" SEXP _riot_ReadVTP(SEXP inputTracts) {
  BEGIN_CPP11
    return cpp11::as_sexp(ReadVTP(cpp11::as_cpp<cpp11::decay_t<const std::string &>>(inputTracts)));
  END_CPP11
}
// fascicleReaders.h
cpp11::writable::list ReadFDS(const std::string & inputTracts);
extern "C" SEXP _riot_ReadFDS(SEXP inputTracts) {
  BEGIN_CPP11
    return cpp11::as_sexp(ReadFDS(cpp11::as_cpp<cpp11::decay_t<const std::string &>>(inputTracts)));
  END_CPP11
}
// fascicleWriters.h
void WriteVTK(cpp11::list inputTracts, const std::string & outputFile);
extern "C" SEXP _riot_WriteVTK(SEXP inputTracts, SEXP outputFile) {
  BEGIN_CPP11
    WriteVTK(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(inputTracts), cpp11::as_cpp<cpp11::decay_t<const std::string &>>(outputFile));
    return R_NilValue;
  END_CPP11
}
// fascicleWriters.h
void WriteVTP(cpp11::list inputTracts, const std::string & outputFile);
extern "C" SEXP _riot_WriteVTP(SEXP inputTracts, SEXP outputFile) {
  BEGIN_CPP11
    WriteVTP(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(inputTracts), cpp11::as_cpp<cpp11::decay_t<const std::string &>>(outputFile));
    return R_NilValue;
  END_CPP11
}
// fascicleWriters.h
void WriteFDS(cpp11::list inputTracts, const std::string & outputFile);
extern "C" SEXP _riot_WriteFDS(SEXP inputTracts, SEXP outputFile) {
  BEGIN_CPP11
    WriteFDS(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(inputTracts), cpp11::as_cpp<cpp11::decay_t<const std::string &>>(outputFile));
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_riot_ReadFDS",  (DL_FUNC) &_riot_ReadFDS,  1},
    {"_riot_ReadVTK",  (DL_FUNC) &_riot_ReadVTK,  1},
    {"_riot_ReadVTP",  (DL_FUNC) &_riot_ReadVTP,  1},
    {"_riot_WriteFDS", (DL_FUNC) &_riot_WriteFDS, 2},
    {"_riot_WriteVTK", (DL_FUNC) &_riot_WriteVTK, 2},
    {"_riot_WriteVTP", (DL_FUNC) &_riot_WriteVTP, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_riot(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
