# Generated by cpp11: do not edit by hand

fun <- function() {
  invisible(.Call(`_riot_fun`))
}

ReadVTK <- function(inputTracts) {
  .Call(`_riot_ReadVTK`, inputTracts)
}

ReadVTP <- function(inputTracts) {
  .Call(`_riot_ReadVTP`, inputTracts)
}

ReadFDS <- function(inputTracts) {
  .Call(`_riot_ReadFDS`, inputTracts)
}

WriteVTK <- function(inputTracts, outputFile) {
  invisible(.Call(`_riot_WriteVTK`, inputTracts, outputFile))
}

WriteVTP <- function(inputTracts, outputFile) {
  invisible(.Call(`_riot_WriteVTP`, inputTracts, outputFile))
}

WriteFDS <- function(inputTracts, outputFile) {
  invisible(.Call(`_riot_WriteFDS`, inputTracts, outputFile))
}
