# Generated by cpp11: do not edit by hand

ReadVTK <- function(inputTracts) {
  .Call(`_riot_ReadVTK`, inputTracts)
}

ReadVTP <- function(inputTracts) {
  .Call(`_riot_ReadVTP`, inputTracts)
}

ReadFDS <- function(inputTracts) {
  .Call(`_riot_ReadFDS`, inputTracts)
}

ReadTRK <- function(inputFile, n_scalars, n_properties, n_count, little_endian, scalar_names, property_names) {
  .Call(`_riot_ReadTRK`, inputFile, n_scalars, n_properties, n_count, little_endian, scalar_names, property_names)
}

WriteVTK <- function(inputTracts, outputFile) {
  invisible(.Call(`_riot_WriteVTK`, inputTracts, outputFile))
}

WriteVTP <- function(inputTracts, outputFile) {
  invisible(.Call(`_riot_WriteVTP`, inputTracts, outputFile))
}

WriteFDS <- function(inputTracts, outputFile) {
  invisible(.Call(`_riot_WriteFDS`, inputTracts, outputFile))
}
