# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ReadVTK <- function(inputTracts, outputFile) {
    invisible(.Call('_riot_ReadVTK', PACKAGE = 'riot', inputTracts, outputFile))
}

ReadVTP <- function(inputTracts, outputFile) {
    invisible(.Call('_riot_ReadVTP', PACKAGE = 'riot', inputTracts, outputFile))
}

